"""add_wfa_models

Revision ID: d3c611757f26
Revises: 10146b097545
Create Date: 2026-04-08 13:20:38.756307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3c611757f26'
down_revision: Union[str, None] = '10146b097545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composition_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('composition_type', sa.String(length=20), nullable=False),
    sa.Column('atomic_strategies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('best_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('best_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('best_sharpe', sa.Float(), nullable=True),
    sa.Column('best_return', sa.Float(), nullable=True),
    sa.Column('total_combinations_tested', sa.Integer(), nullable=True),
    sa.Column('valid_results', sa.Integer(), nullable=True),
    sa.Column('all_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('composition_results', schema=None) as batch_op:
        batch_op.create_index('idx_composition_created', ['created_at'], unique=False)
        batch_op.create_index('idx_composition_type_symbol', ['composition_type', 'symbol'], unique=False)

    op.create_table('wfo_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('is_days', sa.Integer(), nullable=False),
    sa.Column('oos_days', sa.Integer(), nullable=False),
    sa.Column('step_days', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wfo_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_wfo_sessions_created', ['created_at'], unique=False)
        batch_op.create_index('idx_wfo_sessions_status', ['status'], unique=False)
        batch_op.create_index('idx_wfo_sessions_strategy_symbol', ['strategy_type', 'symbol'], unique=False)

    op.create_table('wfo_window_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wfo_session_id', sa.Integer(), nullable=False),
    sa.Column('window_index', sa.Integer(), nullable=False),
    sa.Column('is_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('oos_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('oos_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('best_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('oos_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wfe', sa.Float(), nullable=True),
    sa.Column('param_stability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wfo_window_results', schema=None) as batch_op:
        batch_op.create_index('idx_wfo_windows_index', ['wfo_session_id', 'window_index'], unique=False)
        batch_op.create_index('idx_wfo_windows_session', ['wfo_session_id'], unique=False)

    # 先删除可能存在的旧索引和约束（在 batch 操作之前）
    op.drop_index('idx_backtest_data_source', table_name='backtest_results', if_exists=True)
    op.drop_index('idx_backtest_params_hash', table_name='backtest_results', if_exists=True)
    op.drop_index('idx_equity_snapshots_data_source', table_name='equity_snapshots', if_exists=True)
    op.drop_constraint('paper_account_replay_session_id_key', table_name='paper_account_replay', type_='unique', if_exists=True)
    op.drop_index('idx_paper_account_replay_session_id', table_name='paper_account_replay', if_exists=True)
    op.drop_index('idx_paper_trades_data_source', table_name='paper_trades', if_exists=True)
    op.drop_index('idx_replay_sessions_backtest', table_name='replay_sessions', if_exists=True)
    op.drop_index('idx_replay_sessions_created', table_name='replay_sessions', if_exists=True)
    op.drop_index('idx_replay_sessions_params_hash', table_name='replay_sessions', if_exists=True)
    op.drop_index('idx_replay_sessions_saved', table_name='replay_sessions', if_exists=True)
    op.drop_index('idx_replay_sessions_status', table_name='replay_sessions', if_exists=True)
    op.drop_constraint('replay_sessions_backtest_id_fkey', table_name='replay_sessions', type_='foreignkey', if_exists=True)
    op.drop_constraint('skill_definitions_skill_id_key', table_name='skill_definitions', type_='unique', if_exists=True)
    op.drop_index('idx_skill_definitions_skill_id', table_name='skill_definitions', if_exists=True)
    op.drop_constraint('skill_executions_execution_id_key', table_name='skill_executions', type_='unique', if_exists=True)
    op.drop_index('idx_skill_executions_execution_id', table_name='skill_executions', if_exists=True)
    op.drop_index('idx_skill_executions_parent', table_name='skill_executions', if_exists=True)
    op.drop_index('idx_skill_executions_workflow', table_name='skill_executions', if_exists=True)
    op.drop_index('idx_skill_metrics_skill_id', table_name='skill_metrics', if_exists=True)
    op.drop_constraint('skill_workflows_workflow_id_key', table_name='skill_workflows', type_='unique', if_exists=True)
    op.drop_index('idx_skill_workflows_workflow_id', table_name='skill_workflows', if_exists=True)

    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.alter_column('data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.alter_column('data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('paper_account_replay', schema=None) as batch_op:
        batch_op.alter_column('total_usdt',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index('idx_paper_account_replay_session_id', ['session_id'], unique=True)

    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.alter_column('leverage',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)

    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.alter_column('leverage',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='杠杆倍数（下单时记录），用于回放/限价单匹配时正确传递到持仓与清算价计算',
               existing_nullable=False)
        batch_op.alter_column('funding_fee',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=None,
               nullable=False)
        batch_op.alter_column('mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('replay_sessions', schema=None) as batch_op:
        batch_op.alter_column('params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('is_saved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('equity_snapshot_interval',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='权益快照间隔（秒），范围：60-14400，默认3600（1小时）',
               existing_nullable=False)
        batch_op.alter_column('metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
        # 删除旧的部分索引（001_initial_schema 中的 idx_replay_saved WHERE is_saved = true）
        op.drop_index('idx_replay_saved', table_name='replay_sessions', if_exists=True)
        batch_op.create_index('idx_replay_saved', ['is_saved'], unique=False)

    with op.batch_alter_table('skill_definitions', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Skill唯一标识符',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Skill名称',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Skill描述',
               existing_nullable=True)
        batch_op.alter_column('skill_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Skill类型（如 strategy_generator, optimization_evaluator）',
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Skill分类',
               existing_nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment=None,
               existing_comment='版本号，默认1.0.0',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment=None,
               existing_comment='状态：active（活跃）, inactive（停用）, deprecated（已废弃）',
               existing_nullable=False)
        batch_op.alter_column('input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='输入参数JSON Schema',
               existing_nullable=False)
        batch_op.alter_column('output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='输出结果JSON Schema',
               existing_nullable=False)
        batch_op.alter_column('parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='默认参数配置',
               existing_nullable=False)
        batch_op.alter_column('dependencies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='依赖库列表',
               existing_nullable=False)
        batch_op.alter_column('timeout_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='执行超时时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('max_retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='最大重试次数，默认3',
               existing_nullable=False)
        batch_op.alter_column('concurrency_limit',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='并发限制，默认1',
               existing_nullable=False)
        batch_op.alter_column('implementation_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='实现模块路径',
               existing_nullable=True)
        batch_op.alter_column('code_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='代码内容（可选）',
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='作者',
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='标签列表',
               existing_nullable=False)
        batch_op.alter_column('execution_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='总执行次数',
               existing_nullable=False)
        batch_op.alter_column('success_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='成功执行次数',
               existing_nullable=False)
        batch_op.alter_column('avg_execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='平均执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('last_executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后执行时间',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_skill_definitions_skill_id'), ['skill_id'], unique=True)

    with op.batch_alter_table('skill_executions', schema=None) as batch_op:
        batch_op.alter_column('execution_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='执行唯一标识符',
               existing_nullable=False)
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='关联的Skill ID',
               existing_nullable=False)
        batch_op.alter_column('skill_version',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='执行时的Skill版本',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='执行状态：pending, running, completed, failed, cancelled',
               existing_nullable=False)
        batch_op.alter_column('success',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否执行成功',
               existing_nullable=False)
        batch_op.alter_column('inputs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='输入参数',
               existing_nullable=False)
        batch_op.alter_column('inputs_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='输入参数哈希值，用于幂等去重',
               existing_nullable=True)
        batch_op.alter_column('parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='执行参数配置',
               existing_nullable=False)
        batch_op.alter_column('context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='执行上下文信息',
               existing_nullable=True)
        batch_op.alter_column('result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='执行结果数据',
               existing_nullable=True)
        batch_op.alter_column('error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
        batch_op.alter_column('error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='错误详情',
               existing_nullable=True)
        batch_op.alter_column('execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('queue_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='排队等待时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='开始执行时间',
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
        batch_op.alter_column('parent_execution_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='父执行ID，用于工作流嵌套',
               existing_nullable=True)
        batch_op.alter_column('workflow_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='所属工作流ID',
               existing_nullable=True)
        batch_op.alter_column('executed_by',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               comment=None,
               existing_comment='执行者',
               existing_nullable=True)
        batch_op.alter_column('execution_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='执行标签',
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_skill_executions_execution_id'), ['execution_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_skill_executions_inputs_hash'), ['inputs_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_executions_parent_execution_id'), ['parent_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_executions_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_executions_workflow_id'), ['workflow_id'], unique=False)

    with op.batch_alter_table('skill_metrics', schema=None) as batch_op:
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='关联的Skill ID',
               existing_nullable=False)
        batch_op.alter_column('period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='统计周期开始时间',
               existing_nullable=False)
        batch_op.alter_column('period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='统计周期结束时间',
               existing_nullable=False)
        batch_op.alter_column('period_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='周期类型：hourly, daily, weekly, monthly',
               existing_nullable=False)
        batch_op.alter_column('total_executions',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='总执行次数',
               existing_nullable=False)
        batch_op.alter_column('successful_executions',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='成功执行次数',
               existing_nullable=False)
        batch_op.alter_column('failed_executions',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='失败执行次数',
               existing_nullable=False)
        batch_op.alter_column('cancelled_executions',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='取消执行次数',
               existing_nullable=False)
        batch_op.alter_column('avg_execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='平均执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('min_execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最小执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('max_execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最大执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('avg_queue_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='平均排队时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('success_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='成功率（0-1）',
               existing_nullable=True)
        batch_op.alter_column('error_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='错误类型分布统计',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_skill_metrics_skill_id'), ['skill_id'], unique=False)

    with op.batch_alter_table('skill_workflows', schema=None) as batch_op:
        batch_op.alter_column('workflow_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='工作流唯一标识符',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='工作流名称',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='工作流描述',
               existing_nullable=True)
        batch_op.alter_column('workflow_definition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='工作流步骤定义（JSON）',
               existing_nullable=False)
        batch_op.alter_column('parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='工作流参数配置',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment=None,
               existing_comment='状态：draft（草稿）, active（活跃）, inactive（停用）',
               existing_nullable=False)
        batch_op.alter_column('execution_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='总执行次数',
               existing_nullable=False)
        batch_op.alter_column('success_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='成功执行次数',
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='作者',
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='标签列表',
               existing_nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment=None,
               existing_comment='版本号',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('last_executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后执行时间',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_skill_workflows_workflow_id'), ['workflow_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_workflows', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Skill工作流表：定义多步骤的技能编排流程',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_skill_workflows_workflow_id'))
        batch_op.create_unique_constraint('skill_workflows_workflow_id_key', ['workflow_id'])
        batch_op.create_index('idx_skill_workflows_workflow_id', ['workflow_id'], unique=False)
        batch_op.alter_column('last_executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后执行时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'1.0.0'::character varying"),
               comment='版本号',
               existing_nullable=False)
        batch_op.alter_column('tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               comment='标签列表',
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=100),
               comment='作者',
               existing_nullable=True)
        batch_op.alter_column('success_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='成功执行次数',
               existing_nullable=False)
        batch_op.alter_column('execution_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='总执行次数',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               comment='状态：draft（草稿）, active（活跃）, inactive（停用）',
               existing_nullable=False)
        batch_op.alter_column('parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='工作流参数配置',
               existing_nullable=False)
        batch_op.alter_column('workflow_definition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='工作流步骤定义（JSON）',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment='工作流描述',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               comment='工作流名称',
               existing_nullable=False)
        batch_op.alter_column('workflow_id',
               existing_type=sa.VARCHAR(length=100),
               comment='工作流唯一标识符',
               existing_nullable=False)

    with op.batch_alter_table('skill_metrics', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Skill性能指标表：聚合统计各时间段内的执行性能',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_skill_metrics_skill_id'))
        batch_op.create_index('idx_skill_metrics_skill_id', ['skill_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('error_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='错误类型分布统计',
               existing_nullable=False)
        batch_op.alter_column('success_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='成功率（0-1）',
               existing_nullable=True)
        batch_op.alter_column('avg_queue_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='平均排队时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('max_execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最大执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('min_execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最小执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('avg_execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='平均执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('cancelled_executions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='取消执行次数',
               existing_nullable=False)
        batch_op.alter_column('failed_executions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='失败执行次数',
               existing_nullable=False)
        batch_op.alter_column('successful_executions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='成功执行次数',
               existing_nullable=False)
        batch_op.alter_column('total_executions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='总执行次数',
               existing_nullable=False)
        batch_op.alter_column('period_type',
               existing_type=sa.VARCHAR(length=20),
               comment='周期类型：hourly, daily, weekly, monthly',
               existing_nullable=False)
        batch_op.alter_column('period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='统计周期结束时间',
               existing_nullable=False)
        batch_op.alter_column('period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='统计周期开始时间',
               existing_nullable=False)
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=100),
               comment='关联的Skill ID',
               existing_nullable=False)

    with op.batch_alter_table('skill_executions', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Skill执行记录表：记录每次执行的详细信息和结果',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_skill_executions_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_skill_executions_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_executions_parent_execution_id'))
        batch_op.drop_index(batch_op.f('ix_skill_executions_inputs_hash'))
        batch_op.drop_index(batch_op.f('ix_skill_executions_execution_id'))
        batch_op.create_unique_constraint('skill_executions_execution_id_key', ['execution_id'])
        batch_op.create_index('idx_skill_executions_workflow', ['workflow_id'], unique=False)
        batch_op.create_index('idx_skill_executions_parent', ['parent_execution_id'], unique=False)
        batch_op.create_index('idx_skill_executions_execution_id', ['execution_id'], unique=False)
        batch_op.alter_column('execution_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               comment='执行标签',
               existing_nullable=False)
        batch_op.alter_column('executed_by',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'system'::character varying"),
               comment='执行者',
               existing_nullable=True)
        batch_op.alter_column('workflow_id',
               existing_type=sa.VARCHAR(length=100),
               comment='所属工作流ID',
               existing_nullable=True)
        batch_op.alter_column('parent_execution_id',
               existing_type=sa.VARCHAR(length=100),
               comment='父执行ID，用于工作流嵌套',
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='完成时间',
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='开始执行时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('queue_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='排队等待时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='错误详情',
               existing_nullable=True)
        batch_op.alter_column('error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_nullable=True)
        batch_op.alter_column('result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='执行结果数据',
               existing_nullable=True)
        batch_op.alter_column('context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='执行上下文信息',
               existing_nullable=True)
        batch_op.alter_column('parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='执行参数配置',
               existing_nullable=False)
        batch_op.alter_column('inputs_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='输入参数哈希值，用于幂等去重',
               existing_nullable=True)
        batch_op.alter_column('inputs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='输入参数',
               existing_nullable=False)
        batch_op.alter_column('success',
               existing_type=sa.BOOLEAN(),
               comment='是否执行成功',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='执行状态：pending, running, completed, failed, cancelled',
               existing_nullable=False)
        batch_op.alter_column('skill_version',
               existing_type=sa.VARCHAR(length=20),
               comment='执行时的Skill版本',
               existing_nullable=False)
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=100),
               comment='关联的Skill ID',
               existing_nullable=False)
        batch_op.alter_column('execution_id',
               existing_type=sa.VARCHAR(length=100),
               comment='执行唯一标识符',
               existing_nullable=False)

    with op.batch_alter_table('skill_definitions', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Skill定义表：存储技能的元数据、配置和实现信息',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_skill_definitions_skill_id'))
        batch_op.create_unique_constraint('skill_definitions_skill_id_key', ['skill_id'])
        batch_op.create_index('idx_skill_definitions_skill_id', ['skill_id'], unique=False)
        batch_op.alter_column('last_executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后执行时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('avg_execution_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='平均执行时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('success_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='成功执行次数',
               existing_nullable=False)
        batch_op.alter_column('execution_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='总执行次数',
               existing_nullable=False)
        batch_op.alter_column('tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               comment='标签列表',
               existing_nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=100),
               comment='作者',
               existing_nullable=True)
        batch_op.alter_column('code_content',
               existing_type=sa.TEXT(),
               comment='代码内容（可选）',
               existing_nullable=True)
        batch_op.alter_column('implementation_path',
               existing_type=sa.VARCHAR(length=500),
               comment='实现模块路径',
               existing_nullable=True)
        batch_op.alter_column('concurrency_limit',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               comment='并发限制，默认1',
               existing_nullable=False)
        batch_op.alter_column('max_retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               comment='最大重试次数，默认3',
               existing_nullable=False)
        batch_op.alter_column('timeout_seconds',
               existing_type=sa.INTEGER(),
               comment='执行超时时间（秒）',
               existing_nullable=True)
        batch_op.alter_column('dependencies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               comment='依赖库列表',
               existing_nullable=False)
        batch_op.alter_column('parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='默认参数配置',
               existing_nullable=False)
        batch_op.alter_column('output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='输出结果JSON Schema',
               existing_nullable=False)
        batch_op.alter_column('input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='输入参数JSON Schema',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               comment='状态：active（活跃）, inactive（停用）, deprecated（已废弃）',
               existing_nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'1.0.0'::character varying"),
               comment='版本号，默认1.0.0',
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               comment='Skill分类',
               existing_nullable=True)
        batch_op.alter_column('skill_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Skill类型（如 strategy_generator, optimization_evaluator）',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               comment='Skill描述',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               comment='Skill名称',
               existing_nullable=False)
        batch_op.alter_column('skill_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Skill唯一标识符',
               existing_nullable=False)

    with op.batch_alter_table('replay_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key('replay_sessions_backtest_id_fkey', 'backtest_results', ['backtest_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('idx_replay_saved')
        batch_op.create_index('idx_replay_sessions_status', ['status'], unique=False)
        batch_op.create_index('idx_replay_sessions_saved', ['is_saved'], unique=False, postgresql_where='(is_saved = true)')
        batch_op.create_index('idx_replay_sessions_params_hash', ['params_hash'], unique=False)
        batch_op.create_index('idx_replay_sessions_created', [sa.text('created_at DESC')], unique=False)
        batch_op.create_index('idx_replay_sessions_backtest', ['backtest_id'], unique=False)
        batch_op.alter_column('metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
        batch_op.alter_column('equity_snapshot_interval',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3600'),
               comment='权益快照间隔（秒），范围：60-14400，默认3600（1小时）',
               existing_nullable=False)
        batch_op.alter_column('data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'REPLAY'::character varying"),
               existing_nullable=False)
        batch_op.alter_column('is_saved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
        batch_op.alter_column('params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)

    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.create_index('idx_paper_trades_data_source', ['data_source'], unique=False)
        batch_op.alter_column('data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PAPER'::character varying"),
               existing_nullable=False)
        batch_op.alter_column('mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'paper'::character varying"),
               existing_nullable=False)
        batch_op.alter_column('funding_fee',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=sa.text('0'),
               nullable=True)
        batch_op.alter_column('leverage',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               comment='杠杆倍数（下单时记录），用于回放/限价单匹配时正确传递到持仓与清算价计算',
               existing_nullable=False)

    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.alter_column('leverage',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)

    with op.batch_alter_table('paper_account_replay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_account_replay_session_id'))
        batch_op.drop_index('idx_paper_account_replay_session_id')
        batch_op.create_index('idx_paper_account_replay_session_id', ['session_id'], unique=False)
        batch_op.create_unique_constraint('paper_account_replay_session_id_key', ['session_id'])
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
        batch_op.alter_column('total_usdt',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_equity_snapshots_data_source', ['data_source'], unique=False)
        batch_op.alter_column('data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PAPER'::character varying"),
               existing_nullable=False)

    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.create_index('idx_backtest_params_hash', ['params_hash'], unique=False)
        batch_op.create_index('idx_backtest_data_source', ['data_source'], unique=False)
        batch_op.alter_column('data_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'BACKTEST'::character varying"),
               existing_nullable=False)

    with op.batch_alter_table('wfo_window_results', schema=None) as batch_op:
        batch_op.drop_index('idx_wfo_windows_session')
        batch_op.drop_index('idx_wfo_windows_index')

    op.drop_table('wfo_window_results')
    with op.batch_alter_table('wfo_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_wfo_sessions_strategy_symbol')
        batch_op.drop_index('idx_wfo_sessions_status')
        batch_op.drop_index('idx_wfo_sessions_created')

    op.drop_table('wfo_sessions')
    with op.batch_alter_table('composition_results', schema=None) as batch_op:
        batch_op.drop_index('idx_composition_type_symbol')
        batch_op.drop_index('idx_composition_created')

    op.drop_table('composition_results')
    # ### end Alembic commands ###
