"""add session_id to selection_history

Revision ID: d4293f8c131f
Revises: d3c611757f26
Create Date: 2026-04-12 10:39:21.278550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4293f8c131f'
down_revision: Union[str, None] = 'd3c611757f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selection_history', sa.Column('session_id', sa.String(length=50), nullable=True))
    op.create_index('idx_selection_history_session', 'selection_history', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_selection_history_session', table_name='selection_history')
    op.drop_column('selection_history', 'session_id')
    # ### end Alembic commands ###
